server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myblog
    username: your_postgres_username
    password: your_postgres_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ?? ??? update, ??? validate ?? none ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cloudflare:
  r2:
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    bucket: ${R2_BUCKET}
    region: auto
    endpoint: ${R2_ENDPOINT}

supabase:
  url: ${SUPABASE_URL}
  api-key: ${SUPABASE_SERVICE_ROLE}
